version: '3.2'

services:
  db:
    image: postgres:12.1
    container_name: ads_listing_db
    environment:
      - POSTGRES_DB=ads_listing_development
    ports:
      - "5432:5432"

  redis:
    image: redis:5.0.7
    container_name: ads_listing_redis
    ports:
      - "6379:6379"
